-- MySQL Script generated by MySQL Workbench
-- Thu Jun 25 19:01:40 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema donafacil
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema donafacil
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `donafacil` ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;

USE `donafacil` ;

-- -----------------------------------------------------
-- Table `donafacil`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `donafacil`.`usuario` (
  `id_usuario` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(150) NOT NULL,
  `contrasena` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `tipo_usuario` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX (`correo` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `donafacil`.`organizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `donafacil`.`organizacion` (
  `id_organizaciones` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `nombre_organizacion` VARCHAR(150) NOT NULL,
  `direccion` VARCHAR(205) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `correo` VARCHAR(150) NOT NULL,
  `id_usuario` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_organizaciones`),
  INDEX (`id_usuario` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`id_usuario`)
    REFERENCES `donafacil`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `donafacil`.`campana`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `donafacil`.`campana` (
  `id_campana` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(150) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `fecha` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `meta_recaudacion` DECIMAL(12,2) NOT NULL,
  `estado` VARCHAR(50) NOT NULL,
  `id_organizacion` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_campana`),
  INDEX (`id_organizacion` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`id_organizacion`)
    REFERENCES `donafacil`.`organizacion` (`id_organizaciones`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `donafacil`.`donacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `donafacil`.`donacion` (
  `id_donacion` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `monto` DECIMAL(12,2) NOT NULL,
  `fecha_donacion` DATE NOT NULL,
  `metodo_pago` VARCHAR(50) NOT NULL,
  `estado` VARCHAR(50) NOT NULL,
  `id_usuario` INT NULL DEFAULT NULL,
  `id_campana` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_donacion`),
  INDEX (`id_usuario` ASC) VISIBLE,
  INDEX (`id_campana` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`id_usuario`)
    REFERENCES `donafacil`.`usuario` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT ``
    FOREIGN KEY (`id_campana`)
    REFERENCES `donafacil`.`campana` (`id_campana`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
